package com.poc.batch.config;

import javax.annotation.PostConstruct;
import javax.sql.DataSource;

import org.apache.commons.dbcp2.BasicDataSource;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.PropertySource;
import org.springframework.core.env.Environment;
import org.springframework.core.io.ResourceLoader;
import org.springframework.jdbc.datasource.init.DatabasePopulatorUtils;
import org.springframework.jdbc.datasource.init.ResourceDatabasePopulator;

import java.util.Objects;

@Configuration
@PropertySource("classpath:/batch-h2.properties")
public class DataSourceConfiguration {

    private final Environment environment;

    private final ResourceLoader resourceLoader;

    public DataSourceConfiguration(Environment environment, ResourceLoader resourceLoader) {
        this.environment = environment;
        this.resourceLoader = resourceLoader;
    }

    @PostConstruct
    protected void initialize() {
        ResourceDatabasePopulator populator = new ResourceDatabasePopulator();
        populator.addScript(resourceLoader.getResource(Objects.requireNonNull(environment.getProperty("batch.schema.script"))));
        //Table generated by JPA Annotations
        //populator.addScript(resourceLoader.getResource(Objects.requireNonNull(environment.getProperty("batch.business.schema.script"))));
        populator.setContinueOnError(true);
        DatabasePopulatorUtils.execute(populator, dataSource());
    }

    @Bean(destroyMethod = "close")
    public DataSource dataSource() {
        BasicDataSource dataSource = new BasicDataSource();
        dataSource.setDriverClassName(environment.getProperty("batch.jdbc.driver"));
        dataSource.setUrl(environment.getProperty("batch.jdbc.url"));
        dataSource.setUsername(environment.getProperty("batch.jdbc.user"));
        dataSource.setPassword(environment.getProperty("batch.jdbc.password"));
        return dataSource;
    }
}
